eureka:
    instance:
        hostname: localhost
    client:
        registerWithEureka: true
        fetchRegistry: true
        serviceUrl:
            defaultZone: http://localhost:8070/eureka/
    server:
        wait-time-in-ms-when-sync-empty: 3000
